### ISSUE TITLE
installed apks lack of so file

### ISSUE THREAD

**Issue by haianhsing** [google/bundletool#110]
**Describe the bug**
I create a aab file with android studio, then run the command:
 `java -jar bundletool .jar build-apks --bundle=main.aab --out=main.apks`
and
`java -jar bundletool.jar install-apks --apks==main.apks`
While I run the app, and find that lack of so file.
However,while I run the command:
`adb shell dumpsys package packageName | grep split`
it return 
`splits=[base, condig.arm64_v8a, config.xxxhpdi, config.zh]`
So, what's the problem

**Bundletool version(s) affected**
Version: [0.10.2]

**Stacktrace**
```
2019-08-12 17:52:32.252 15634-15634/? A/libc: CANNOT LINK EXECUTABLE "/data/user/0/com.free.unblock.proxy.hotspot.vpn/cache/c_pie_openvpn.arm64-v8a": library "libopenvpn.so" not found
2019-08-12 17:52:32.253 15634-15634/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 15634 (c_pie_openvpn.a)
2019-08-12 17:52:32.253 919-1999/? D/EnterpriseController: netId is 0
2019-08-12 17:52:32.253 919-1999/? D/Netd: getNetworkForDns: using netid 502 for uid 10024
2019-08-12 17:52:32.253 919-1999/? D/DnsProxyListener: DNSDBG::dns addrinfo af 0
2019-08-12 17:52:32.256 860-860/? E/audit: type=1400 audit(1565603552.238:1844): avc:  denied  { read } for  pid=599 comm="debuggerd64" name="c_pie_openvpn.arm64-v8a" dev="dm-1" ino=133458 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=file permissive=0 SEPF_SECMOBILE_7.0_0004
2019-08-12 17:52:32.256 860-860/? E/audit: type=1300 audit(1565603552.238:1844): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7fb542a5e0 a2=80000 a3=0 items=0 ppid=1 pid=599 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="debuggerd64" exe="/system/bin/debuggerd64" subj=u:r:debuggerd:s0 key=(null)
2019-08-12 17:52:32.257 860-860/? E/audit: type=1327 audit(1565603552.238:1844): proctitle="/system/bin/debuggerd64"
2019-08-12 17:52:32.257 860-860/? E/audit: type=1320 audit(1565603552.238:1844): 
```

**To Reproduce**
1. build the aab file
2. upload to googleplay, download and install or use bundletool tool to install 
3. run the app and find the error 

**Expected behavior**
app run with no error.

**Known workaround**
build the apk directly and install or create the apks and install standalone-arm64_v8a_xxxhdpi.apk

**Environment:**
OS: [Sansumgs s7 with Android 7.0, Honor 20 with Android 9.0, and more]

**Additional context**

I hope to solve this problem as soon as possible. Thanks.

**Comment by plecesne** [comment]
It looks like a bug in whatever library is trying to read the native libraries. It is expecting the .so file to be extracted out of the APK during installation, which may not happen since Android M.

Bundletool leaves the native libraries uncompressed in the APK by default so that those libraries don't have to be extracted out of the APK and can be read directly from the APK, leading to faster installation times, and saved space on the users' devices.

A workaround exists by setting the flag "android.bundle.enableUncompressedNativeLibs=false" in the Gradle options. However, beware that this will effectively kill all the benefits I've mentioned above.

Are you reading the native libraries yourself or is this from an SDK you depend on? If from an SDK, would you be able to share which one so that we can file a bug for them to fix this issue?

**Comment by haianhsing** [comment]
@plecesne I don't think it's a native libraries problem. Before I update the android gradle plugin tools version to `com.android.tools.build:gradle:3.4.2` and update andoirdx support library, it work well.

**Comment by plecesne** [comment]
What version did you upgrade the Android Gradle plugin from?

**Comment by haianhsing** [comment]
@plecesne 
- gradle from `https\://services.gradle.org/distributions/gradle-4.10.1-all.zip` to `https\://services.gradle.org/distributions/gradle-5.1.1-all.zip` 
- gradle plugin from `com.android.tools.build:gradle:3.2.0` to `com.android.tools.build:gradle:3.4.2`

**Comment by plecesne** [comment]
Thank you.
I confirm that what I described above is what is happening. Android Gradle plugin 3.4.2 has introduced support for uncompressed native libraries in the App Bundle.

**Comment by haianhsing** [comment]
@plecesne 
Thank you for your patient answer.
I think setting the flag "android.bundle.enableUncompressedNativeLibs=false" in the Gradle options is the best solution right now and I decided to do that.
Should I close the issue or wait for the better solution?

**Comment by plecesne** [comment]
As I mentioned, the solution already exists and is for the developers to fix their code to use standard Android APIs to read the native libraries.

If you're not reading the `.so` file yourself, would you be able to share which library you are using which is doing so? The stacktrace suggests `libopenvpn.so` -- if that's the library, what project or Maven dependency did you add to depend on this library? We can file a bug with them to fix their code.

**Comment by haianhsing** [comment]
@plecesne 
It is an old version of an open source project: `https://github.com/schwabe/ics-openvpn`.
Maybe new version has been resolved the problem. 
However, I'm not going to use the new version for the time being for some other reasons.
Finally, thank you very much.

**Comment by assilMekki** [comment]
Hello,
sorry for commenting on and lod issue, but I wanted to ask if you guys found any solution for this, I get the same error log :
 `CANNOT LINK EXECUTABLE library "libopenvpn.so" not found`

gradle : 
`https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`
gradle plugin : 
`com.android.tools.build:gradle:3.6.3`

setting `android.bundle.enableUncompressedNativeLibs=false` didnt solve it either
